### ISSUE TITLE
Knowledge SDK cache causing articles not to load

### ISSUE THREAD

**Issue by cammace** [forcedotcom/ServiceSDK-Android#120]
Hey there, we've recently integrated the Salesforce Knowledge SDK into our application and on my end, things seem to be working correctly but we've been getting reports from our beta community that in some cases, the knowledge articles fail to load; showing the "Oops something went wrong..." message. My colleague was able to reproduce this and found that clearing the app cache resolved the issue. We have logging enabled for our debug builds but haven't seen any error pointing to the culprit issue. Reading through the docs, I know you guys cache the articles on the device using encryption but it looks like there's no way to disable this behavior, only an option to clear the cache. I do get this runtime exception when opening the knowledge activity, even when the articles do successfully load in:

```
2019-02-05 10:07:36.359 8532-8828/com.doordash.driverapp.debug W/KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createException(Parcel.java:1956)
        at android.os.Parcel.readException(Parcel.java:1910)
        at android.os.Parcel.readException(Parcel.java:1860)
        at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
        at android.security.KeyStore.get(KeyStore.java:195)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:149)
        at java.security.KeyStoreSpi.engineEntryInstanceOf(KeyStoreSpi.java:579)
        at java.security.KeyStore.entryInstanceOf(KeyStore.java:1631)
        at com.salesforce.android.encryption.g.a(KeySourceV23.java:113)
        at com.salesforce.android.encryption.g.a(KeySourceV23.java:69)
        at com.salesforce.android.encryption.i.a(SalesforceEncryption.java:68)
        at com.salesforce.android.encryption.i.a(SalesforceEncryption.java:123)
        at com.salesforce.android.database.a.c(DatabaseAccess.java:150)
        at com.salesforce.android.database.a.a(DatabaseAccess.java:90)
        at com.salesforce.android.database.f.a(DatabaseWriteJob.java:80)
        at com.salesforce.android.service.common.utilities.h.d$c.run(JobQueue.java:140)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-02-05 10:07:36.367 1742-1742/? I/keystore: 1 0
```

Is there something I'm missing when it comes to initializing the SDK. In previous versions, we had to specifically provide a key upon initialization of Salesforce but from the docs, this is no longer a requirement, so we removed it. These articles aren't a secret so encrypting the cache doesn't really need to take place.

On a related note, is there any callback we could subscribe to which lets us know when the articles fail to load so that we can attempt to clear the cache or give the users an alternative way to reach out to our support team? Would `async.onError` be the right API or should there be something like below exposed in the SDK?

```java
KnowledgeUI.configure(uiConfiguration))
    .createClient(requireContext())
    .onResult((async, uIClient) -> {

        ...
        uIClient.onArticleLoadError(() -> ...);
        uIClient.launchHome(requireActivity());
    });
});
```

**Comment by rileymacdonald-sf** [comment]
Let me take some time to investigate this further and I'll get back to you.

**Comment by rileymacdonald-sf** [comment]
@cammace Can you please clarify which devices/os this issue is reproducible on?

**Comment by cammace** [comment]
Hey @rileymacdonald-sf, thanks for getting back to me. As for overall reproducibility, we haven't found the culprit of the issue and seems to happen randomly. No specific device causes this and we are using version `4.2.1` of the knowledge artifact. I take it even if I have logging disabled, `SQLiteException` will be logged as an error or will logging need to be enabled (we currently disable for release builds). I'll keep my eye open for this next time along with notifying my colleauges to do the same, Though none of them recall seeing any specific errors logged in logcat. 

As for my original suggestion, I did a lot of digging into the SDK and docs and still haven't found a callback I can observe to know when an API call goes bad, specifically the one that fetches all the articles at knowledge home launch. Along with the close callback, would it be possible to add an error callback of some kind for these, hopefully rare, cases? The reason for this is so I can display our contact support buttons (ViewAdditions) immediately to the user rather than having them hidden behind articles which they can never reach when these errors occur.

**Comment by rileymacdonald-sf** [comment]
@cammace we've opened a ticket internally to track this issue along with another ticket to further investigate modifying the API to support exposing this type of error. Closing this issue.

**Comment by cammace** [comment]
I was finally able to identify the issue which was related to ProGuard stripping out the `sqlcipher` classes. Would be lovely if in a future release of the SDKs a `consumer-proguard-rules.pro` was included in the AAR for all these proguard rules which would eliminate the requirement for me to manually maintain the rules on my end.
